### ISSUE TITLE
subView background colour change?

### ISSUE THREAD

**Issue by hemo87** [LaurentiuUngur/LUAutocompleteView#13]
I've changed the background colour to the cell, but when the cells are removed you can see the white view behind retracting. 

Background colour of cell all ok
![screen shot 2019-01-06 at 17 38 40](https://user-images.githubusercontent.com/9624935/50739554-17b82e80-11da-11e9-8be8-ea72af64ca76.png)

When clearing textField it exposed the white view that I'm unable to change the colour of?
![screen shot 2019-01-06 at 17 38 47](https://user-images.githubusercontent.com/9624935/50739555-1a1a8880-11da-11e9-9717-f244c17fa891.png)

**Comment by LaurentiuUngur** [comment]
Please also set same background colour to the autocomplete view.

**Comment by hemo87** [comment]
Tried that with no joy I'm afraid.

So far I've got 

`        autocompleteView.autocompleteCell = CustomAutocompleteTableViewCell.self
        view.addSubview(autocompleteView)
        
        autocompleteView.textField = exerciseTextField
        autocompleteView.dataSource = self
        autocompleteView.delegate = self
        autocompleteView.rowHeight = 45
        autocompleteView.backgroundColor = UIColor.flatBlack
       // autocompleteView.layer.backgroundColor = UIColor.flatBlack.cgColor
       // autocompleteView.tintColor = UIColor.flatBlack`


And



`import UIKit
import LUAutocompleteView

final class CustomAutocompleteTableViewCell: LUAutocompleteTableViewCell {
    // MARK: - Base Class Overrides
    
    override func set(text: String) {
        textLabel?.text = text
        textLabel?.textColor = UIColor.flatWhite
        backgroundColor = UIColor.flatBlack
        textLabel?.font = UIFont(name: "Impact", size: 17)
        //backgroundView?.tintColor = UIColor.flatBlack
        //backgroundView?.backgroundColor = UIColor.flatBlack
       // backgroundView?.layer.backgroundColor = UIColor.flatBlack.cgColor
        //window?.backgroundColor = UIColor.flatBlack
        //window?.layer.backgroundColor = UIColor.flatBlack.cgColor
        
    }
    

}`

None of the lines commented out worked.

**Comment by LaurentiuUngur** [comment]
Try please `autocompleteView.subviews.forEach { $0.backgroundColor = UIColor.flatBlack }`

**Comment by hemo87** [comment]
That did the trick! Thanks a lot for the quick reply!
