### ISSUE TITLE
Cannot convert value of type '[String : AnyObject]?' to expected argument type '[NSAttributedStringKey : Any]?'

### ISSUE THREAD

**Issue by jofax** [LaurentiuUngur/LUAutocompleteView#5]
Cannot convert value of type '[String : AnyObject]?' to expected argument type '[NSAttributedStringKey : Any]?'

I had changed:
public var textAttributes: [String: Any]?

To

public var textAttributes: [NSAttributedStringKey : Any]?

**Comment by LaurentiuUngur** [comment]
Please use latest version.
