### ISSUE TITLE
Issue with Constraints

### ISSUE THREAD

**Issue by michael-mckenna** [LaurentiuUngur/LUAutocompleteView#6]
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutXAxisAnchor:0x1c0c6f180 "LUAutocompleteView.LUAutocompleteView:0x109e991f0.leading"> and <NSLayoutXAxisAnchor:0x1c0c61480 "UITextField:0x10a0f7400.leading"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.'

I have a textfield in a cell in a static table view, and I got this error after setting `autocompleteView.textField = myTextField` in `viewDidLoad()`

**Comment by LaurentiuUngur** [comment]
As the error said `they have no common ancestor`. Add autocomplete view as subview of cell. That should fix the problem.
